/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TaskType = IDL.Variant({
  'followSocialMedia' : IDL.Null,
  'tapTapTask' : IDL.Null,
  'aiPhotoEdit' : IDL.Null,
  'watchYouTubeVideo' : IDL.Null,
  'aiVideoEdit' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'rewardCents' : IDL.Nat,
  'description' : IDL.Text,
  'taskType' : TaskType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EServiceType = IDL.Variant({
  'passport' : IDL.Null,
  'visa' : IDL.Null,
  'landServices' : IDL.Null,
  'nidCopy' : IDL.Null,
  'mobileRecharge' : IDL.Null,
});
export const EServiceRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'serviceType' : EServiceType,
  'requestDetails' : IDL.Text,
  'user' : IDL.Principal,
});
export const VerificationStatus = IDL.Record({
  'bankAccountVerified' : IDL.Bool,
  'emailVerified' : IDL.Bool,
  'nidVerified' : IDL.Bool,
});
export const MicroLoanRequest = IDL.Record({
  'id' : IDL.Text,
  'monthlyPaymentCents' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'amountCents' : IDL.Nat,
  'purpose' : IDL.Text,
  'verificationStatus' : VerificationStatus,
  'repaymentMonths' : IDL.Nat,
});
export const WithdrawMethod = IDL.Variant({
  'bank' : IDL.Record({
    'branch' : IDL.Text,
    'routingNumber' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
  }),
  'cash' : IDL.Null,
  'global' : IDL.Record({ 'provider' : IDL.Text, 'accountNumber' : IDL.Text }),
  'mobile' : IDL.Record({ 'provider' : IDL.Text, 'accountNumber' : IDL.Text }),
});
export const WithdrawRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'method' : WithdrawMethod,
  'user' : IDL.Principal,
  'amountCents' : IDL.Nat,
  'comment' : IDL.Opt(IDL.Text),
  'verificationStatus' : VerificationStatus,
  'requestedAt' : IDL.Int,
});
export const UserBan = IDL.Record({
  'banType' : IDL.Variant({ 'permanent' : IDL.Null, 'temporary' : IDL.Int }),
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'issuedBy' : IDL.Principal,
  'reason' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'profileScore' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'verificationStatus' : VerificationStatus,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const TaskCompletion = IDL.Record({
  'completionTime' : IDL.Int,
  'rewardCents' : IDL.Nat,
  'taskId' : IDL.Text,
});
export const DPSRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'amountCents' : IDL.Nat,
  'termMonths' : IDL.Nat,
  'purpose' : IDL.Text,
  'verificationStatus' : VerificationStatus,
});
export const Referral = IDL.Record({
  'referrer' : IDL.Principal,
  'timestamp' : IDL.Int,
  'referee' : IDL.Principal,
});
export const TapToEarnState = IDL.Record({
  'coinBalance' : IDL.Nat,
  'tapCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTaskToCatalog' : IDL.Func([Task], [], []),
  'approveEServiceRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'approveMicroLoan' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Variant({ 'permanent' : IDL.Null, 'temporary' : IDL.Int }),
      ],
      [],
      [],
    ),
  'calculateReferralBonus' : IDL.Func([], [IDL.Nat], ['query']),
  'claimTapToEarnCoins' : IDL.Func([IDL.Null], [IDL.Nat], []),
  'getAllEServiceRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(EServiceRequest)))],
      ['query'],
    ),
  'getAllMicroLoanRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(MicroLoanRequest)))],
      ['query'],
    ),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(WithdrawRequest)))],
      ['query'],
    ),
  'getBanStatus' : IDL.Func([IDL.Principal], [IDL.Opt(UserBan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyCompletedTasks' : IDL.Func([], [IDL.Vec(TaskCompletion)], ['query']),
  'getMyDPSRequests' : IDL.Func([], [IDL.Vec(DPSRequest)], ['query']),
  'getMyDocuments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getMyEServiceRequests' : IDL.Func([], [IDL.Vec(EServiceRequest)], ['query']),
  'getMyMicroLoanRequests' : IDL.Func(
      [],
      [IDL.Vec(MicroLoanRequest)],
      ['query'],
    ),
  'getMyReferralCode' : IDL.Func([], [IDL.Text], ['query']),
  'getMyReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
  'getMyWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawRequest)],
      ['query'],
    ),
  'getTapToEarnState' : IDL.Func([], [TapToEarnState], ['query']),
  'getTaskCatalog' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'registerReferral' : IDL.Func([IDL.Text], [], []),
  'registerTap' : IDL.Func([IDL.Null], [], []),
  'registerTaps' : IDL.Func([IDL.Nat], [], []),
  'removeTaskFromCatalog' : IDL.Func([IDL.Text], [], []),
  'requestDPS' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Text], []),
  'requestEService' : IDL.Func([EServiceType, IDL.Text], [IDL.Text], []),
  'requestMicroLoan' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Text], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, WithdrawMethod], [IDL.Text], []),
  'resetTapCount' : IDL.Func([IDL.Null], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startTask' : IDL.Func([IDL.Text], [], []),
  'submitTaskCompletion' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'uploadSensitiveDocument' : IDL.Func(
      [IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'verifyDocument' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TaskType = IDL.Variant({
    'followSocialMedia' : IDL.Null,
    'tapTapTask' : IDL.Null,
    'aiPhotoEdit' : IDL.Null,
    'watchYouTubeVideo' : IDL.Null,
    'aiVideoEdit' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'rewardCents' : IDL.Nat,
    'description' : IDL.Text,
    'taskType' : TaskType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EServiceType = IDL.Variant({
    'passport' : IDL.Null,
    'visa' : IDL.Null,
    'landServices' : IDL.Null,
    'nidCopy' : IDL.Null,
    'mobileRecharge' : IDL.Null,
  });
  const EServiceRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'serviceType' : EServiceType,
    'requestDetails' : IDL.Text,
    'user' : IDL.Principal,
  });
  const VerificationStatus = IDL.Record({
    'bankAccountVerified' : IDL.Bool,
    'emailVerified' : IDL.Bool,
    'nidVerified' : IDL.Bool,
  });
  const MicroLoanRequest = IDL.Record({
    'id' : IDL.Text,
    'monthlyPaymentCents' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'amountCents' : IDL.Nat,
    'purpose' : IDL.Text,
    'verificationStatus' : VerificationStatus,
    'repaymentMonths' : IDL.Nat,
  });
  const WithdrawMethod = IDL.Variant({
    'bank' : IDL.Record({
      'branch' : IDL.Text,
      'routingNumber' : IDL.Text,
      'accountHolderName' : IDL.Text,
      'bankName' : IDL.Text,
      'accountNumber' : IDL.Text,
    }),
    'cash' : IDL.Null,
    'global' : IDL.Record({
      'provider' : IDL.Text,
      'accountNumber' : IDL.Text,
    }),
    'mobile' : IDL.Record({
      'provider' : IDL.Text,
      'accountNumber' : IDL.Text,
    }),
  });
  const WithdrawRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'method' : WithdrawMethod,
    'user' : IDL.Principal,
    'amountCents' : IDL.Nat,
    'comment' : IDL.Opt(IDL.Text),
    'verificationStatus' : VerificationStatus,
    'requestedAt' : IDL.Int,
  });
  const UserBan = IDL.Record({
    'banType' : IDL.Variant({ 'permanent' : IDL.Null, 'temporary' : IDL.Int }),
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'issuedBy' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'profileScore' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'verificationStatus' : VerificationStatus,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const TaskCompletion = IDL.Record({
    'completionTime' : IDL.Int,
    'rewardCents' : IDL.Nat,
    'taskId' : IDL.Text,
  });
  const DPSRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'amountCents' : IDL.Nat,
    'termMonths' : IDL.Nat,
    'purpose' : IDL.Text,
    'verificationStatus' : VerificationStatus,
  });
  const Referral = IDL.Record({
    'referrer' : IDL.Principal,
    'timestamp' : IDL.Int,
    'referee' : IDL.Principal,
  });
  const TapToEarnState = IDL.Record({
    'coinBalance' : IDL.Nat,
    'tapCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTaskToCatalog' : IDL.Func([Task], [], []),
    'approveEServiceRequest' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'approveMicroLoan' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Variant({ 'permanent' : IDL.Null, 'temporary' : IDL.Int }),
        ],
        [],
        [],
      ),
    'calculateReferralBonus' : IDL.Func([], [IDL.Nat], ['query']),
    'claimTapToEarnCoins' : IDL.Func([IDL.Null], [IDL.Nat], []),
    'getAllEServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(EServiceRequest)))],
        ['query'],
      ),
    'getAllMicroLoanRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(MicroLoanRequest)))],
        ['query'],
      ),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(WithdrawRequest)))],
        ['query'],
      ),
    'getBanStatus' : IDL.Func([IDL.Principal], [IDL.Opt(UserBan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyCompletedTasks' : IDL.Func([], [IDL.Vec(TaskCompletion)], ['query']),
    'getMyDPSRequests' : IDL.Func([], [IDL.Vec(DPSRequest)], ['query']),
    'getMyDocuments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getMyEServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(EServiceRequest)],
        ['query'],
      ),
    'getMyMicroLoanRequests' : IDL.Func(
        [],
        [IDL.Vec(MicroLoanRequest)],
        ['query'],
      ),
    'getMyReferralCode' : IDL.Func([], [IDL.Text], ['query']),
    'getMyReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
    'getMyWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawRequest)],
        ['query'],
      ),
    'getTapToEarnState' : IDL.Func([], [TapToEarnState], ['query']),
    'getTaskCatalog' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'registerReferral' : IDL.Func([IDL.Text], [], []),
    'registerTap' : IDL.Func([IDL.Null], [], []),
    'registerTaps' : IDL.Func([IDL.Nat], [], []),
    'removeTaskFromCatalog' : IDL.Func([IDL.Text], [], []),
    'requestDPS' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Text], []),
    'requestEService' : IDL.Func([EServiceType, IDL.Text], [IDL.Text], []),
    'requestMicroLoan' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Text], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat, WithdrawMethod], [IDL.Text], []),
    'resetTapCount' : IDL.Func([IDL.Null], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startTask' : IDL.Func([IDL.Text], [], []),
    'submitTaskCompletion' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'uploadSensitiveDocument' : IDL.Func(
        [IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'verifyDocument' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };