/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DPSRequest {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'user' : Principal,
  'amountCents' : bigint,
  'termMonths' : bigint,
  'purpose' : string,
  'verificationStatus' : VerificationStatus,
}
export interface EServiceRequest {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'serviceType' : EServiceType,
  'requestDetails' : string,
  'user' : Principal,
}
export type EServiceType = { 'passport' : null } |
  { 'visa' : null } |
  { 'landServices' : null } |
  { 'nidCopy' : null } |
  { 'mobileRecharge' : null };
export type ExternalBlob = Uint8Array;
export interface MicroLoanRequest {
  'id' : string,
  'monthlyPaymentCents' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'user' : Principal,
  'amountCents' : bigint,
  'purpose' : string,
  'verificationStatus' : VerificationStatus,
  'repaymentMonths' : bigint,
}
export interface Referral {
  'referrer' : Principal,
  'timestamp' : bigint,
  'referee' : Principal,
}
export interface TapToEarnState { 'coinBalance' : bigint, 'tapCount' : bigint }
export interface Task {
  'id' : string,
  'title' : string,
  'rewardCents' : bigint,
  'description' : string,
  'taskType' : TaskType,
}
export interface TaskCompletion {
  'completionTime' : bigint,
  'rewardCents' : bigint,
  'taskId' : string,
}
export type TaskType = { 'followSocialMedia' : null } |
  { 'tapTapTask' : null } |
  { 'aiPhotoEdit' : null } |
  { 'watchYouTubeVideo' : null } |
  { 'aiVideoEdit' : null };
export interface UserBan {
  'banType' : { 'permanent' : null } |
    { 'temporary' : bigint },
  'user' : Principal,
  'timestamp' : bigint,
  'issuedBy' : Principal,
  'reason' : string,
}
export interface UserProfile {
  'profileScore' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
  'location' : string,
  'verificationStatus' : VerificationStatus,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerificationStatus {
  'bankAccountVerified' : boolean,
  'emailVerified' : boolean,
  'nidVerified' : boolean,
}
export type WithdrawMethod = {
    'bank' : {
      'branch' : string,
      'routingNumber' : string,
      'accountHolderName' : string,
      'bankName' : string,
      'accountNumber' : string,
    }
  } |
  { 'cash' : null } |
  { 'global' : { 'provider' : string, 'accountNumber' : string } } |
  { 'mobile' : { 'provider' : string, 'accountNumber' : string } };
export interface WithdrawRequest {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'method' : WithdrawMethod,
  'user' : Principal,
  'amountCents' : bigint,
  'comment' : [] | [string],
  'verificationStatus' : VerificationStatus,
  'requestedAt' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTaskToCatalog' : ActorMethod<[Task], undefined>,
  'approveEServiceRequest' : ActorMethod<[Principal, string], undefined>,
  'approveMicroLoan' : ActorMethod<[Principal, string], undefined>,
  'approveWithdrawal' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<
    [Principal, string, { 'permanent' : null } | { 'temporary' : bigint }],
    undefined
  >,
  'calculateReferralBonus' : ActorMethod<[], bigint>,
  'claimTapToEarnCoins' : ActorMethod<[null], bigint>,
  'getAllEServiceRequests' : ActorMethod<
    [],
    Array<[Principal, Array<EServiceRequest>]>
  >,
  'getAllMicroLoanRequests' : ActorMethod<
    [],
    Array<[Principal, Array<MicroLoanRequest>]>
  >,
  'getAllWithdrawalRequests' : ActorMethod<
    [],
    Array<[Principal, Array<WithdrawRequest>]>
  >,
  'getBanStatus' : ActorMethod<[Principal], [] | [UserBan]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBalance' : ActorMethod<[], bigint>,
  'getMyCompletedTasks' : ActorMethod<[], Array<TaskCompletion>>,
  'getMyDPSRequests' : ActorMethod<[], Array<DPSRequest>>,
  'getMyDocuments' : ActorMethod<[], Array<[string, string, boolean]>>,
  'getMyEServiceRequests' : ActorMethod<[], Array<EServiceRequest>>,
  'getMyMicroLoanRequests' : ActorMethod<[], Array<MicroLoanRequest>>,
  'getMyReferralCode' : ActorMethod<[], string>,
  'getMyReferrals' : ActorMethod<[], Array<Referral>>,
  'getMyWithdrawalRequests' : ActorMethod<[], Array<WithdrawRequest>>,
  'getTapToEarnState' : ActorMethod<[], TapToEarnState>,
  'getTaskCatalog' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBanned' : ActorMethod<[Principal], boolean>,
  'registerReferral' : ActorMethod<[string], undefined>,
  'registerTap' : ActorMethod<[null], undefined>,
  'registerTaps' : ActorMethod<[bigint], undefined>,
  'removeTaskFromCatalog' : ActorMethod<[string], undefined>,
  'requestDPS' : ActorMethod<[bigint, bigint, string], string>,
  'requestEService' : ActorMethod<[EServiceType, string], string>,
  'requestMicroLoan' : ActorMethod<[bigint, string, bigint], string>,
  'requestWithdrawal' : ActorMethod<[bigint, WithdrawMethod], string>,
  'resetTapCount' : ActorMethod<[null], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startTask' : ActorMethod<[string], undefined>,
  'submitTaskCompletion' : ActorMethod<[string, string], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'uploadSensitiveDocument' : ActorMethod<[string, ExternalBlob], string>,
  'verifyDocument' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];