/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    profileScore: bigint;
    name: string;
    email: string;
    phone: string;
    location: string;
    verificationStatus: VerificationStatus;
    avatar?: ExternalBlob;
}
export interface EServiceRequest {
    id: string;
    status: Variant_pending_approved_rejected;
    serviceType: EServiceType;
    requestDetails: string;
    user: Principal;
}
export interface TaskCompletion {
    completionTime: bigint;
    rewardCents: bigint;
    taskId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserBan {
    banType: {
        __kind__: "permanent";
        permanent: null;
    } | {
        __kind__: "temporary";
        temporary: bigint;
    };
    user: Principal;
    timestamp: bigint;
    issuedBy: Principal;
    reason: string;
}
export interface Task {
    id: string;
    title: string;
    rewardCents: bigint;
    description: string;
    taskType: TaskType;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface WithdrawRequest {
    id: string;
    status: Variant_pending_approved_rejected;
    method: WithdrawMethod;
    user: Principal;
    amountCents: bigint;
    comment?: string;
    verificationStatus: VerificationStatus;
    requestedAt: bigint;
}
export interface DPSRequest {
    id: string;
    status: Variant_pending_approved_rejected;
    user: Principal;
    amountCents: bigint;
    termMonths: bigint;
    purpose: string;
    verificationStatus: VerificationStatus;
}
export type WithdrawMethod = {
    __kind__: "bank";
    bank: {
        branch: string;
        routingNumber: string;
        accountHolderName: string;
        bankName: string;
        accountNumber: string;
    };
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "global";
    global: {
        provider: string;
        accountNumber: string;
    };
} | {
    __kind__: "mobile";
    mobile: {
        provider: string;
        accountNumber: string;
    };
};
export interface VerificationStatus {
    bankAccountVerified: boolean;
    emailVerified: boolean;
    nidVerified: boolean;
}
export interface Referral {
    referrer: Principal;
    timestamp: bigint;
    referee: Principal;
}
export interface MicroLoanRequest {
    id: string;
    monthlyPaymentCents: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    amountCents: bigint;
    purpose: string;
    verificationStatus: VerificationStatus;
    repaymentMonths: bigint;
}
export interface TapToEarnState {
    coinBalance: bigint;
    tapCount: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EServiceType {
    passport = "passport",
    visa = "visa",
    landServices = "landServices",
    nidCopy = "nidCopy",
    mobileRecharge = "mobileRecharge"
}
export enum TaskType {
    followSocialMedia = "followSocialMedia",
    tapTapTask = "tapTapTask",
    aiPhotoEdit = "aiPhotoEdit",
    watchYouTubeVideo = "watchYouTubeVideo",
    aiVideoEdit = "aiVideoEdit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTaskToCatalog(task: Task): Promise<void>;
    approveEServiceRequest(user: Principal, requestId: string): Promise<void>;
    approveMicroLoan(user: Principal, requestId: string): Promise<void>;
    approveWithdrawal(user: Principal, requestId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(user: Principal, reason: string, banType: {
        __kind__: "permanent";
        permanent: null;
    } | {
        __kind__: "temporary";
        temporary: bigint;
    }): Promise<void>;
    calculateReferralBonus(): Promise<bigint>;
    claimTapToEarnCoins(arg0: null): Promise<bigint>;
    getAllEServiceRequests(): Promise<Array<[Principal, Array<EServiceRequest>]>>;
    getAllMicroLoanRequests(): Promise<Array<[Principal, Array<MicroLoanRequest>]>>;
    getAllWithdrawalRequests(): Promise<Array<[Principal, Array<WithdrawRequest>]>>;
    getBanStatus(user: Principal): Promise<UserBan | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBalance(): Promise<bigint>;
    getMyCompletedTasks(): Promise<Array<TaskCompletion>>;
    getMyDPSRequests(): Promise<Array<DPSRequest>>;
    getMyDocuments(): Promise<Array<[string, string, boolean]>>;
    getMyEServiceRequests(): Promise<Array<EServiceRequest>>;
    getMyMicroLoanRequests(): Promise<Array<MicroLoanRequest>>;
    getMyReferralCode(): Promise<string>;
    getMyReferrals(): Promise<Array<Referral>>;
    getMyWithdrawalRequests(): Promise<Array<WithdrawRequest>>;
    getTapToEarnState(): Promise<TapToEarnState>;
    getTaskCatalog(): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isUserBanned(user: Principal): Promise<boolean>;
    registerReferral(referrerCode: string): Promise<void>;
    registerTap(arg0: null): Promise<void>;
    registerTaps(tapCount: bigint): Promise<void>;
    removeTaskFromCatalog(taskId: string): Promise<void>;
    requestDPS(amountCents: bigint, termMonths: bigint, purpose: string): Promise<string>;
    requestEService(serviceType: EServiceType, requestDetails: string): Promise<string>;
    requestMicroLoan(amountCents: bigint, purpose: string, repaymentMonths: bigint): Promise<string>;
    requestWithdrawal(amountCents: bigint, method: WithdrawMethod): Promise<string>;
    resetTapCount(arg0: null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startTask(taskId: string): Promise<void>;
    submitTaskCompletion(taskId: string, proof: string): Promise<void>;
    unbanUser(user: Principal): Promise<void>;
    uploadSensitiveDocument(documentType: string, encryptedContent: ExternalBlob): Promise<string>;
    verifyDocument(docId: string): Promise<void>;
}
import type { DPSRequest as _DPSRequest, EServiceRequest as _EServiceRequest, EServiceType as _EServiceType, ExternalBlob as _ExternalBlob, MicroLoanRequest as _MicroLoanRequest, Task as _Task, TaskType as _TaskType, UserBan as _UserBan, UserProfile as _UserProfile, UserRole as _UserRole, VerificationStatus as _VerificationStatus, WithdrawMethod as _WithdrawMethod, WithdrawRequest as _WithdrawRequest, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTaskToCatalog(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTaskToCatalog(to_candid_Task_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTaskToCatalog(to_candid_Task_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveEServiceRequest(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveEServiceRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveEServiceRequest(arg0, arg1);
            return result;
        }
    }
    async approveMicroLoan(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveMicroLoan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveMicroLoan(arg0, arg1);
            return result;
        }
    }
    async approveWithdrawal(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal, arg1: string, arg2: {
        __kind__: "permanent";
        permanent: null;
    } | {
        __kind__: "temporary";
        temporary: bigint;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0, arg1, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0, arg1, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async calculateReferralBonus(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateReferralBonus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateReferralBonus();
            return result;
        }
    }
    async claimTapToEarnCoins(arg0: null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.claimTapToEarnCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimTapToEarnCoins(arg0);
            return result;
        }
    }
    async getAllEServiceRequests(): Promise<Array<[Principal, Array<EServiceRequest>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEServiceRequests();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEServiceRequests();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMicroLoanRequests(): Promise<Array<[Principal, Array<MicroLoanRequest>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMicroLoanRequests();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMicroLoanRequests();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWithdrawalRequests(): Promise<Array<[Principal, Array<WithdrawRequest>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBanStatus(arg0: Principal): Promise<UserBan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBanStatus(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBanStatus(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalance();
            return result;
        }
    }
    async getMyCompletedTasks(): Promise<Array<TaskCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCompletedTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCompletedTasks();
            return result;
        }
    }
    async getMyDPSRequests(): Promise<Array<DPSRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDPSRequests();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDPSRequests();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDocuments(): Promise<Array<[string, string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDocuments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDocuments();
            return result;
        }
    }
    async getMyEServiceRequests(): Promise<Array<EServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEServiceRequests();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEServiceRequests();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMicroLoanRequests(): Promise<Array<MicroLoanRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMicroLoanRequests();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMicroLoanRequests();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReferralCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReferralCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReferralCode();
            return result;
        }
    }
    async getMyReferrals(): Promise<Array<Referral>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReferrals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReferrals();
            return result;
        }
    }
    async getMyWithdrawalRequests(): Promise<Array<WithdrawRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWithdrawalRequests();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWithdrawalRequests();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTapToEarnState(): Promise<TapToEarnState> {
        if (this.processError) {
            try {
                const result = await this.actor.getTapToEarnState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTapToEarnState();
            return result;
        }
    }
    async getTaskCatalog(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskCatalog();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskCatalog();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserBanned(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserBanned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserBanned(arg0);
            return result;
        }
    }
    async registerReferral(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerReferral(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerReferral(arg0);
            return result;
        }
    }
    async registerTap(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTap(arg0);
            return result;
        }
    }
    async registerTaps(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerTaps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerTaps(arg0);
            return result;
        }
    }
    async removeTaskFromCatalog(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTaskFromCatalog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTaskFromCatalog(arg0);
            return result;
        }
    }
    async requestDPS(arg0: bigint, arg1: bigint, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestDPS(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestDPS(arg0, arg1, arg2);
            return result;
        }
    }
    async requestEService(arg0: EServiceType, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestEService(to_candid_EServiceType_n55(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestEService(to_candid_EServiceType_n55(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async requestMicroLoan(arg0: bigint, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestMicroLoan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestMicroLoan(arg0, arg1, arg2);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint, arg1: WithdrawMethod): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawMethod_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawMethod_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async resetTapCount(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetTapCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetTapCount(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTask(arg0);
            return result;
        }
    }
    async submitTaskCompletion(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTaskCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTaskCompletion(arg0, arg1);
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async uploadSensitiveDocument(arg0: string, arg1: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadSensitiveDocument(arg0, await to_candid_ExternalBlob_n61(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadSensitiveDocument(arg0, await to_candid_ExternalBlob_n61(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyDocument(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDocument(arg0);
            return result;
        }
    }
}
function from_candid_DPSRequest_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DPSRequest): DPSRequest {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_EServiceRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EServiceRequest): EServiceRequest {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_EServiceType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EServiceType): EServiceType {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MicroLoanRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MicroLoanRequest): MicroLoanRequest {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_UserBan_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserBan): UserBan {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawMethod_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawMethod): WithdrawMethod {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawRequest_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawRequest): WithdrawRequest {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserBan]): UserBan | null {
    return value.length === 0 ? null : from_candid_UserBan_n37(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n41(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    serviceType: _EServiceType;
    requestDetails: string;
    user: Principal;
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    serviceType: EServiceType;
    requestDetails: string;
    user: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_EServiceType_n21(_uploadFile, _downloadFile, value.serviceType),
        requestDetails: value.requestDetails,
        user: value.user
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    monthlyPaymentCents: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    user: Principal;
    amountCents: bigint;
    purpose: string;
    verificationStatus: _VerificationStatus;
    repaymentMonths: bigint;
}): {
    id: string;
    monthlyPaymentCents: bigint;
    status: Variant_pending_approved_rejected;
    user: Principal;
    amountCents: bigint;
    purpose: string;
    verificationStatus: VerificationStatus;
    repaymentMonths: bigint;
} {
    return {
        id: value.id,
        monthlyPaymentCents: value.monthlyPaymentCents,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        user: value.user,
        amountCents: value.amountCents,
        purpose: value.purpose,
        verificationStatus: value.verificationStatus,
        repaymentMonths: value.repaymentMonths
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    method: _WithdrawMethod;
    user: Principal;
    amountCents: bigint;
    comment: [] | [string];
    verificationStatus: _VerificationStatus;
    requestedAt: bigint;
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    method: WithdrawMethod;
    user: Principal;
    amountCents: bigint;
    comment?: string;
    verificationStatus: VerificationStatus;
    requestedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        method: from_candid_WithdrawMethod_n33(_uploadFile, _downloadFile, value.method),
        user: value.user,
        amountCents: value.amountCents,
        comment: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.comment)),
        verificationStatus: value.verificationStatus,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    banType: {
        permanent: null;
    } | {
        temporary: bigint;
    };
    user: Principal;
    timestamp: bigint;
    issuedBy: Principal;
    reason: string;
}): {
    banType: {
        __kind__: "permanent";
        permanent: null;
    } | {
        __kind__: "temporary";
        temporary: bigint;
    };
    user: Principal;
    timestamp: bigint;
    issuedBy: Principal;
    reason: string;
} {
    return {
        banType: from_candid_variant_n39(_uploadFile, _downloadFile, value.banType),
        user: value.user,
        timestamp: value.timestamp,
        issuedBy: value.issuedBy,
        reason: value.reason
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileScore: bigint;
    name: string;
    email: string;
    phone: string;
    location: string;
    verificationStatus: _VerificationStatus;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    profileScore: bigint;
    name: string;
    email: string;
    phone: string;
    location: string;
    verificationStatus: VerificationStatus;
    avatar?: ExternalBlob;
}> {
    return {
        profileScore: value.profileScore,
        name: value.name,
        email: value.email,
        phone: value.phone,
        location: value.location,
        verificationStatus: value.verificationStatus,
        avatar: record_opt_to_undefined(await from_candid_opt_n43(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    user: Principal;
    amountCents: bigint;
    termMonths: bigint;
    purpose: string;
    verificationStatus: _VerificationStatus;
}): {
    id: string;
    status: Variant_pending_approved_rejected;
    user: Principal;
    amountCents: bigint;
    termMonths: bigint;
    purpose: string;
    verificationStatus: VerificationStatus;
} {
    return {
        id: value.id,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        user: value.user,
        amountCents: value.amountCents,
        termMonths: value.termMonths,
        purpose: value.purpose,
        verificationStatus: value.verificationStatus
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    rewardCents: bigint;
    description: string;
    taskType: _TaskType;
}): {
    id: string;
    title: string;
    rewardCents: bigint;
    description: string;
    taskType: TaskType;
} {
    return {
        id: value.id,
        title: value.title,
        rewardCents: value.rewardCents,
        description: value.description,
        taskType: from_candid_TaskType_n53(_uploadFile, _downloadFile, value.taskType)
    };
}
function from_candid_tuple_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_EServiceRequest>]): [Principal, Array<EServiceRequest>] {
    return [
        value[0],
        from_candid_vec_n17(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_MicroLoanRequest>]): [Principal, Array<MicroLoanRequest>] {
    return [
        value[0],
        from_candid_vec_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_WithdrawRequest>]): [Principal, Array<WithdrawRequest>] {
    return [
        value[0],
        from_candid_vec_n30(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    passport: null;
} | {
    visa: null;
} | {
    landServices: null;
} | {
    nidCopy: null;
} | {
    mobileRecharge: null;
}): EServiceType {
    return "passport" in value ? EServiceType.passport : "visa" in value ? EServiceType.visa : "landServices" in value ? EServiceType.landServices : "nidCopy" in value ? EServiceType.nidCopy : "mobileRecharge" in value ? EServiceType.mobileRecharge : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bank: {
        branch: string;
        routingNumber: string;
        accountHolderName: string;
        bankName: string;
        accountNumber: string;
    };
} | {
    cash: null;
} | {
    global: {
        provider: string;
        accountNumber: string;
    };
} | {
    mobile: {
        provider: string;
        accountNumber: string;
    };
}): {
    __kind__: "bank";
    bank: {
        branch: string;
        routingNumber: string;
        accountHolderName: string;
        bankName: string;
        accountNumber: string;
    };
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "global";
    global: {
        provider: string;
        accountNumber: string;
    };
} | {
    __kind__: "mobile";
    mobile: {
        provider: string;
        accountNumber: string;
    };
} {
    return "bank" in value ? {
        __kind__: "bank",
        bank: value.bank
    } : "cash" in value ? {
        __kind__: "cash",
        cash: value.cash
    } : "global" in value ? {
        __kind__: "global",
        global: value.global
    } : "mobile" in value ? {
        __kind__: "mobile",
        mobile: value.mobile
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permanent: null;
} | {
    temporary: bigint;
}): {
    __kind__: "permanent";
    permanent: null;
} | {
    __kind__: "temporary";
    temporary: bigint;
} {
    return "permanent" in value ? {
        __kind__: "permanent",
        permanent: value.permanent
    } : "temporary" in value ? {
        __kind__: "temporary",
        temporary: value.temporary
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    followSocialMedia: null;
} | {
    tapTapTask: null;
} | {
    aiPhotoEdit: null;
} | {
    watchYouTubeVideo: null;
} | {
    aiVideoEdit: null;
}): TaskType {
    return "followSocialMedia" in value ? TaskType.followSocialMedia : "tapTapTask" in value ? TaskType.tapTapTask : "aiPhotoEdit" in value ? TaskType.aiPhotoEdit : "watchYouTubeVideo" in value ? TaskType.watchYouTubeVideo : "aiVideoEdit" in value ? TaskType.aiVideoEdit : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_EServiceRequest>]>): Array<[Principal, Array<EServiceRequest>]> {
    return value.map((x)=>from_candid_tuple_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EServiceRequest>): Array<EServiceRequest> {
    return value.map((x)=>from_candid_EServiceRequest_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_MicroLoanRequest>]>): Array<[Principal, Array<MicroLoanRequest>]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MicroLoanRequest>): Array<MicroLoanRequest> {
    return value.map((x)=>from_candid_MicroLoanRequest_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_WithdrawRequest>]>): Array<[Principal, Array<WithdrawRequest>]> {
    return value.map((x)=>from_candid_tuple_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawRequest>): Array<WithdrawRequest> {
    return value.map((x)=>from_candid_WithdrawRequest_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DPSRequest>): Array<DPSRequest> {
    return value.map((x)=>from_candid_DPSRequest_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n51(_uploadFile, _downloadFile, x));
}
function to_candid_EServiceType_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EServiceType): _EServiceType {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TaskType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawMethod_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawMethod): _WithdrawMethod {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileScore: bigint;
    name: string;
    email: string;
    phone: string;
    location: string;
    verificationStatus: VerificationStatus;
    avatar?: ExternalBlob;
}): Promise<{
    profileScore: bigint;
    name: string;
    email: string;
    phone: string;
    location: string;
    verificationStatus: _VerificationStatus;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        profileScore: value.profileScore,
        name: value.name,
        email: value.email,
        phone: value.phone,
        location: value.location,
        verificationStatus: value.verificationStatus,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n61(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    rewardCents: bigint;
    description: string;
    taskType: TaskType;
}): {
    id: string;
    title: string;
    rewardCents: bigint;
    description: string;
    taskType: _TaskType;
} {
    return {
        id: value.id,
        title: value.title,
        rewardCents: value.rewardCents,
        description: value.description,
        taskType: to_candid_TaskType_n10(_uploadFile, _downloadFile, value.taskType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    followSocialMedia: null;
} | {
    tapTapTask: null;
} | {
    aiPhotoEdit: null;
} | {
    watchYouTubeVideo: null;
} | {
    aiVideoEdit: null;
} {
    return value == TaskType.followSocialMedia ? {
        followSocialMedia: null
    } : value == TaskType.tapTapTask ? {
        tapTapTask: null
    } : value == TaskType.aiPhotoEdit ? {
        aiPhotoEdit: null
    } : value == TaskType.watchYouTubeVideo ? {
        watchYouTubeVideo: null
    } : value == TaskType.aiVideoEdit ? {
        aiVideoEdit: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "permanent";
    permanent: null;
} | {
    __kind__: "temporary";
    temporary: bigint;
}): {
    permanent: null;
} | {
    temporary: bigint;
} {
    return value.__kind__ === "permanent" ? {
        permanent: value.permanent
    } : value.__kind__ === "temporary" ? {
        temporary: value.temporary
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EServiceType): {
    passport: null;
} | {
    visa: null;
} | {
    landServices: null;
} | {
    nidCopy: null;
} | {
    mobileRecharge: null;
} {
    return value == EServiceType.passport ? {
        passport: null
    } : value == EServiceType.visa ? {
        visa: null
    } : value == EServiceType.landServices ? {
        landServices: null
    } : value == EServiceType.nidCopy ? {
        nidCopy: null
    } : value == EServiceType.mobileRecharge ? {
        mobileRecharge: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "bank";
    bank: {
        branch: string;
        routingNumber: string;
        accountHolderName: string;
        bankName: string;
        accountNumber: string;
    };
} | {
    __kind__: "cash";
    cash: null;
} | {
    __kind__: "global";
    global: {
        provider: string;
        accountNumber: string;
    };
} | {
    __kind__: "mobile";
    mobile: {
        provider: string;
        accountNumber: string;
    };
}): {
    bank: {
        branch: string;
        routingNumber: string;
        accountHolderName: string;
        bankName: string;
        accountNumber: string;
    };
} | {
    cash: null;
} | {
    global: {
        provider: string;
        accountNumber: string;
    };
} | {
    mobile: {
        provider: string;
        accountNumber: string;
    };
} {
    return value.__kind__ === "bank" ? {
        bank: value.bank
    } : value.__kind__ === "cash" ? {
        cash: value.cash
    } : value.__kind__ === "global" ? {
        global: value.global
    } : value.__kind__ === "mobile" ? {
        mobile: value.mobile
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
